name: divnr
favicon: null
layout_spectrum: 0.738297276198864
typography_spectrum: 0.7593144287820905
title: divnr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#8c8c8c'
    - '#ec3c2b'
    - '#006dbf'
  brandStrength: 0.625
  lightness: 0.21516411029733717
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
