name: divnr
favicon: null
layout_spectrum: 0.738297276198864
typography_spectrum: 0.7593144287820905
title: divnr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5238595330156386
  lightness: 0.21516411029733717
  saturation: 0.2792575496714562
  rhythmicContrast: 0.956499332562089
purpose: []
